// Shared string dictionary for the app-shell layout components (sidebar,
// top bar, document rail, search/upload/settings centers, footer). Lives
// here rather than in each component because these components are split
// across files but still read one cohesive dict via useT(STR) -- see
// i18n.jsx for the per-file-dict convention this otherwise follows.
export const STR = {
  ja: {
    brand: 'LLM Wiki',
    brandSubtitle: 'ナレッジワークスペース',

    pinned: {
      home: 'スタート',
      graph: 'グラフ',
      upload: 'アップロード',
      settings: '設定',
      chat: 'チャット',
      glossary: '用語集',
      topics: 'トピック',
      documents: 'ドキュメント',
    },

    shell: {
      chat: 'チャット',
      graph: 'グラフ',
      upload: 'アップロード',
      queue: 'ジョブキュー',
      glossary: '用語集',
      explorer: 'エクスプローラー',
      topics: 'トピック',
      settings: '設定',
      newChat: '新しいチャット',
      recentQuestions: '最近の質問',
      viewAll: 'すべて表示',
      noRecentQuestions: '最近の質問はありません。',
      collapseSidebar: 'サイドバーを折りたたむ',
      expandSidebar: 'サイドバーを展開',
      history: '履歴',
      bookmark: 'ブックマーク',
      profile: 'プロフィール',
      collapseDocuments: 'ドキュメントを閉じる',
      showDocuments: 'ドキュメントを表示',
      closeRightSidebar: '右サイドバーを閉じる',
      switchToDocs: 'ドキュメント',
      switchToTopics: 'トピック',
      terms: '利用規約',
      privacy: 'プライバシーポリシー',
      footerCopyright: (year) => `${year} MESW LLM Wiki`,
    },

    topbar: {
      placeholder: 'ノートまたはトピックを検索…',
      keywordSearch: 'キーワード検索',
      searchDocs: '検索',
      searching: '検索中…',
      emptyQuery: '検索語を入力してください。',
    },

    pages: {
      uploadTitle: 'アップロード',
      uploadText: 'Markdown またはソースファイルをナレッジグラフに取り込みます。',
      settingsTitle: '設定',
      settingsText: 'エージェントの動作とリクエスト単位の上書きを設定します。',
      glossaryTitle: '用語集',
      glossaryText: '用語集は後で実装します。',
      searchTitle: '検索結果',
      searchText: (q, n) => `「${q}」に一致するノートが ${n} 件見つかりました。`,
      searchEmptyTitle: '検索結果がありません',
      searchEmptyText: (q) => `「${q}」に一致するノートは見つかりませんでした。`,
      searchIdleTitle: '検索してください',
      searchIdleText: '上部の検索バーからノートまたはトピックを検索できます。',
    },

    rightRail: {
      documentsTitle: 'ドキュメント',
      documentsSubtitle: '元ドキュメントのナビゲーション',
      topicsTitle: 'トピック',
      topicsSubtitle: 'トピック別に整理',
      explorerTab: 'エクスプローラー',
      sourcesTab: 'ソース',
      sourcesTitle: '回答のソース',
      sourcesSubtitle: (n) => `${n} 件のソースノード`,
      viewAnswer: '回答を開く',
      usedSource: '使用済みソース',
      missingSource: 'ソースノードが見つかりません。',
      noSources: 'この回答にソースノードはありません。',
    },

    markdownFrame: {
      fallbackTitle: 'ドキュメント',
      hint: 'ドキュメント領域をダブルクリックすると編集できます。折りたたむとこの表示を閉じます。',
      working: '処理中…',
      back: '戻る',
      backTitle: '前の画面に戻る',
      collapse: '折りたたむ',
      collapseTitle: 'ドキュメントを折りたたむ',
    },

    searchResults: {
      open: '開く',
      sourceNote: 'ソースノート',
      agentNote: 'エージェントノート',
      unknownSource: 'ソース不明',
      noSummary: '概要はありません。',
      resultCount: (n) => `${n} 件`,
    },

    startingWrite: '書き込みジョブを開始中...',
    queued: '書き込みジョブをキューに入れました。',
    queuedPos: (p) => `書き込みジョブをキューに入れました。順位 ${p}。`,
    writing: 'グラフに書き込み中：埋め込み、リンク、クラスタリング...',
    writeFinished: '書き込みが完了しました。',
    writeFailed: '書き込みジョブが失敗しました。',
    writeCancelled: '書き込みジョブがキャンセルされました。',
    statusOf: (s) => `書き込みジョブの状態: ${s}`,

    couldNotOpen: (m) => `ノートを開けませんでした: ${m}`,
    startingUpdate: 'グラフの更新を開始中...',
    nodeUpdated: 'ノードをグラフで更新しました。',
    savedNodeUpdated: '保存しました。ノードをグラフで更新しました。',
    updateFailed: (m) => `更新に失敗しました: ${m}`,
    startingDelete: '削除ジョブを開始中...',
    nodeDeleted: 'ノードをグラフから削除しました。',
    noteDeleted: 'ノートを削除しました。',
    deleteFailed: (m) => `削除に失敗しました: ${m}`,

    startingWriteGraph: 'グラフへの書き込みを開始中...',
    mdAdded: 'Markdown をグラフに追加しました。',
    mdAddedOpened: 'Markdown をグラフに追加し、ワークスペースで開きました。',
    chunkedAdded: (n) =>
      `大型ドキュメントを ${n} 件のページに分割してグラフに追加しました。`,
    chunkProgress: (stage) => `処理中: ${stage}`,
    addFailed: (m) => `追加に失敗しました: ${m}`,
    addedToGraph: 'グラフに追加しました。',
    savedOpened: 'グラフに保存し、ワークスペースで開きました。',
    savedToGraph: 'グラフに保存しました。',
    savedWikiNote: 'wiki ノートとして保存し、ソースにリンクしました。',
    saveFailed: (m) => `保存に失敗しました: ${m}`,

    noMatch: '一致するノートはありません。',
    searchFailed: (m) => `検索に失敗しました: ${m}`,

    agentNote: 'エージェントノート',
    sourceNote: 'ソースノート',
    untitled: '無題',
    answer: '回答',

    fullDocMeta: (n) => `${n} ページから再構成した完全なドキュメント。`,
    unsavedDraft: '未保存の下書き。',
    answerMetaSteps: (n) => `${n} ステップで生成。確認・編集してから wiki に追加してください。`,
    answerMeta: '確認・編集してから wiki に追加してください。',

    explorer: (n) => `エクスプローラー ${n}`,
    searching: (who, q) => (who ? `${who} · “${q}” を検索中` : `“${q}” を検索中`),
    pagesFound: (c) => `${c} 件のページが見つかりました`,
    spawned: (n) => `${n} 人のエクスプローラーを起動`,
    exploring: (who, n) => `${who} · ${n} を探索中`,
    reading: (who, n) => `${who} · ${n} を読み中`,
    following: (who, n, ne) => `${who} · ${n} からリンクをたどり中 (${ne})`,
    subDone: (who, c) => `${who} · 完了 (${c} ソース)`,
    compiling: '回答をコンパイル中…',
    routeReuse: '既存のノートを再利用して回答します',
    routeShallow: '浅い検索で回答します（証拠が十分）',
    routeDeep: '深い調査を開始します',
    diagramBuilding: '図を作成中…',
    diagramReady: '図の準備完了',
    diagramFailed: '図を描画できませんでした',

    working: '作業中…',
    answerReady: (steps) => `${steps} ステップで回答ができました。`,
    agentStopped: 'エージェントを停止しました',
    agentStoppedText: 'エージェントの実行は停止されました。',
    stopAgentFailed: (m) => `停止に失敗しました: ${m}`,
    openedReview: 'ワークスペースで開きました →。確認してから wiki に追加してください。',
    foundNoBody: 'ソースは見つかりましたが、回答本文がありません。',
    foundNoBodyText: (c, steps) =>
      `エージェントは ${steps} ステップで ${c} 件のソースを集めましたが、最終的な回答を生成しませんでした。`,
    requestFailed: 'リクエストが失敗しました',

    collapseDocs: 'ドキュメントを隠す',
    showDocs: 'ドキュメントを表示',
    loadingGraph: 'グラフを読み込み中…',
    cannotReach: 'バックエンドに接続できません',

    closeTab: 'タブを閉じる',
    nothingOpen: '何も開いていません',
    homeHint: (hasDocs) =>
      `左のパネルからドキュメントを開くか${hasDocs ? '' : '（取り込み後）'}、チャットでエージェントに作成を依頼してください。`,

    assimTitle:
      '新しいノードは今すぐ検索できます。ランキングとクラスタリングはバックグラウンドで進行中です。',
    assimBadge: 'グラフを整理中…',
  },

  en: {
    brand: 'LLM Wiki',
    brandSubtitle: 'Knowledge workspace',

    pinned: {
      home: 'Start',
      graph: 'Graph',
      upload: 'Upload',
      settings: 'Settings',
      chat: 'Chat',
      glossary: 'Glossary',
      topics: 'Topics',
      documents: 'Documents',
    },

    shell: {
      chat: 'Chat',
      graph: 'Graph',
      upload: 'Upload',
      queue: 'Job queue',
      glossary: 'Glossary',
      explorer: 'Explorer',
      topics: 'Topics',
      settings: 'Settings',
      newChat: 'New chat',
      recentQuestions: 'Recent questions',
      viewAll: 'View all',
      noRecentQuestions: 'No recent questions yet.',
      collapseSidebar: 'Collapse sidebar',
      expandSidebar: 'Expand sidebar',
      history: 'History',
      bookmark: 'Bookmark',
      profile: 'Profile',
      collapseDocuments: 'Hide documents',
      showDocuments: 'Show documents',
      closeRightSidebar: 'Close right sidebar',
      switchToDocs: 'Docs',
      switchToTopics: 'Topics',
      terms: 'Terms',
      privacy: 'Privacy Policy',
      footerCopyright: (year) => `${year} MESW LLM Wiki`,
    },

    topbar: {
      placeholder: 'Search notes or topics…',
      keywordSearch: 'Keyword search',
      searchDocs: 'Search docs',
      searching: 'Searching…',
      emptyQuery: 'Enter a search term.',
    },

    pages: {
      uploadTitle: 'Upload',
      uploadText: 'Import Markdown or source files into the knowledge graph.',
      settingsTitle: 'Settings',
      settingsText: 'Configure agent behavior and request-level overrides.',
      glossaryTitle: 'Glossary',
      glossaryText: 'Glossary will be implemented later.',
      searchTitle: 'Search results',
      searchText: (q, n) => `${n} matching notes found for “${q}”.`,
      searchEmptyTitle: 'No search results',
      searchEmptyText: (q) => `No matching notes were found for “${q}”.`,
      searchIdleTitle: 'Search knowledge',
      searchIdleText: 'Use the top search bar to find notes or topics.',
    },

    rightRail: {
      documentsTitle: 'Documents',
      documentsSubtitle: 'Original document navigation',
      topicsTitle: 'Topics',
      topicsSubtitle: 'Arranged by topic',
      explorerTab: 'Explorer',
      sourcesTab: 'Sources',
      sourcesTitle: 'Answer sources',
      sourcesSubtitle: (n) => `${n} source node${n === 1 ? '' : 's'}`,
      viewAnswer: 'View answer',
      usedSource: 'Used source',
      missingSource: 'Source node not found.',
      noSources: 'This answer has no source nodes.',
    },

    markdownFrame: {
      fallbackTitle: 'Document',
      hint: 'Double-click the document area to edit. Collapse closes this view.',
      working: 'Working…',
      back: 'Back',
      backTitle: 'Back to previous screen',
      collapse: 'Collapse',
      collapseTitle: 'Collapse document',
    },

    searchResults: {
      open: 'Open',
      sourceNote: 'Source note',
      agentNote: 'Agent note',
      unknownSource: 'Unknown source',
      noSummary: 'No summary available.',
      resultCount: (n) => `${n} results`,
    },

    startingWrite: 'Starting write job...',
    queued: 'Queued write job.',
    queuedPos: (p) => `Queued write job. Position ${p}.`,
    writing: 'Writing to the graph: embedding, linking, and clustering...',
    writeFinished: 'Write finished.',
    writeFailed: 'Write job failed.',
    writeCancelled: 'Write job was cancelled.',
    statusOf: (s) => `Write job status: ${s}`,

    couldNotOpen: (m) => `Could not open note: ${m}`,
    startingUpdate: 'Starting graph update...',
    nodeUpdated: 'Node updated in the graph.',
    savedNodeUpdated: 'Saved. Node updated in the graph.',
    updateFailed: (m) => `Update failed: ${m}`,
    startingDelete: 'Starting delete job...',
    nodeDeleted: 'Node deleted from the graph.',
    noteDeleted: 'Note deleted.',
    deleteFailed: (m) => `Delete failed: ${m}`,

    startingWriteGraph: 'Starting graph write...',
    mdAdded: 'Markdown added to the graph.',
    mdAddedOpened: 'Markdown added to the graph and opened in the workspace.',
    chunkedAdded: (n) =>
      `Large document was split into ${n} pages and added to the graph.`,
    chunkProgress: (stage) => `Working: ${stage}`,
    addFailed: (m) => `Add failed: ${m}`,
    addedToGraph: 'Added to the graph.',
    savedOpened: 'Saved to the graph and opened in the workspace.',
    savedToGraph: 'Saved to the graph.',
    savedWikiNote: 'Saved as a wiki note, linked to its sources.',
    saveFailed: (m) => `Save failed: ${m}`,

    noMatch: 'No matching notes.',
    searchFailed: (m) => `Search failed: ${m}`,

    agentNote: 'Agent note',
    sourceNote: 'Source note',
    untitled: 'Untitled',
    answer: 'Answer',

    fullDocMeta: (n) => `Full document reconstructed from ${n} pages.`,
    unsavedDraft: 'Unsaved draft.',
    answerMetaSteps: (n) => `Generated in ${n} steps. Review, edit, then add it to the wiki.`,
    answerMeta: 'Review, edit, then add it to the wiki.',

    explorer: (n) => `Explorer ${n}`,
    searching: (who, q) => (who ? `${who} · searching “${q}”` : `searching “${q}”`),
    pagesFound: (c) => `${c} pages found`,
    spawned: (n) => `spawned ${n} explorers`,
    exploring: (who, n) => `${who} · exploring ${n}`,
    reading: (who, n) => `${who} · reading ${n}`,
    following: (who, n, ne) => `${who} · following links from ${n} (${ne})`,
    subDone: (who, c) => `${who} · done (${c} sources)`,
    compiling: 'compiling answer…',
    routeReuse: 'reusing an existing note',
    routeShallow: 'answering from a shallow lookup',
    routeDeep: 'starting deep research',
    diagramBuilding: 'building diagram…',
    diagramReady: 'diagram ready',
    diagramFailed: 'could not render diagram',

    working: 'Working…',
    answerReady: (steps) => `Answer ready in ${steps} steps.`,
    agentStopped: 'Agent stopped',
    agentStoppedText: 'The agent run was stopped.',
    stopAgentFailed: (m) => `Stop failed: ${m}`,
    openedReview: 'Opened in the workspace →. Review it, then add it to the wiki.',
    foundNoBody: 'Found sources, but no answer body.',
    foundNoBodyText: (c, steps) =>
      `The agent gathered ${c} sources in ${steps} steps but produced no final answer.`,
    requestFailed: 'Request failed',

    collapseDocs: 'Collapse documents',
    showDocs: 'Show documents',
    loadingGraph: 'Loading graph…',
    cannotReach: 'Cannot reach the backend',

    closeTab: 'Close tab',
    nothingOpen: 'Nothing open',
    homeHint: (hasDocs) =>
      `Open a document from the left panel${hasDocs ? '' : ' once you ingest some'}, or ask the agent in the chat to write one.`,

    assimTitle:
      'New nodes are searchable now; ranking and clustering are catching up in the background.',
    assimBadge: 'Assimilating graph…',
  },
}
