#!/usr/bin/env python3

from image_core import llm_judges, mermaid_media, pipelines

# Keep mutable module-level knobs for existing callers (e.g. parser/server.py).
MARKDOWN_FOLDER = pipelines.MARKDOWN_FOLDER
FILE_CONCURRENCY = pipelines.FILE_CONCURRENCY
OUTPUT_FILE = pipelines.OUTPUT_FILE

OPENAI_BASE_URL = llm_judges.OPENAI_BASE_URL
OPENAI_API_KEY = llm_judges.OPENAI_API_KEY
OPENAI_MODEL = llm_judges.OPENAI_MODEL

CONCURRENCY = pipelines.CONCURRENCY
TEMPERATURE = llm_judges.TEMPERATURE
TOP_P = llm_judges.TOP_P
MAX_TOKENS = llm_judges.MAX_TOKENS
LLM_THINKING_TIMEOUT_SECONDS = llm_judges.LLM_THINKING_TIMEOUT_SECONDS
LLM_FALLBACK_TIMEOUT_SECONDS = llm_judges.LLM_FALLBACK_TIMEOUT_SECONDS
JUDGE_TEMPERATURE = llm_judges.JUDGE_TEMPERATURE

MERMAID_PUPPETEER_CONFIG_FILE = mermaid_media.MERMAID_PUPPETEER_CONFIG_FILE
ENABLE_MERMAID_DIAGRAMS = mermaid_media.ENABLE_MERMAID_DIAGRAMS
VALIDATE_MERMAID = mermaid_media.VALIDATE_MERMAID
MERMAID_CLI_BIN = mermaid_media.MERMAID_CLI_BIN
MERMAID_REPAIR_ATTEMPTS = mermaid_media.MERMAID_REPAIR_ATTEMPTS
MERMAID_PARSE_TIMEOUT_SECONDS = mermaid_media.MERMAID_PARSE_TIMEOUT_SECONDS
MERMAID_CLI_REQUIRED = mermaid_media.MERMAID_CLI_REQUIRED

ENABLE_MERMAID_VISUAL_MATCH_LOOP = mermaid_media.ENABLE_MERMAID_VISUAL_MATCH_LOOP
MERMAID_VISUAL_MATCH_ATTEMPTS = mermaid_media.MERMAID_VISUAL_MATCH_ATTEMPTS
MERMAID_VISUAL_MATCH_GOOD_ENOUGH_SCORE = (
    mermaid_media.MERMAID_VISUAL_MATCH_GOOD_ENOUGH_SCORE
)
MERMAID_RENDER_TIMEOUT_SECONDS = mermaid_media.MERMAID_RENDER_TIMEOUT_SECONDS
INCLUDE_VISUAL_JUDGE_NOTE = mermaid_media.INCLUDE_VISUAL_JUDGE_NOTE

ENABLE_DESCRIPTION_COVERAGE_LOOP = llm_judges.ENABLE_DESCRIPTION_COVERAGE_LOOP
DESCRIPTION_COVERAGE_ATTEMPTS = llm_judges.DESCRIPTION_COVERAGE_ATTEMPTS
DESCRIPTION_COVERAGE_GOOD_ENOUGH_SCORE = (
    llm_judges.DESCRIPTION_COVERAGE_GOOD_ENOUGH_SCORE
)
INCLUDE_COVERAGE_JUDGE_NOTE = llm_judges.INCLUDE_COVERAGE_JUDGE_NOTE
ENABLE_SHALLOW_RETRY = llm_judges.ENABLE_SHALLOW_RETRY


def _sync_globals_to_modules() -> None:
    # llm_judges.py
    llm_judges.OPENAI_BASE_URL = OPENAI_BASE_URL
    llm_judges.OPENAI_API_KEY = OPENAI_API_KEY
    llm_judges.OPENAI_MODEL = OPENAI_MODEL
    llm_judges.TEMPERATURE = TEMPERATURE
    llm_judges.TOP_P = TOP_P
    llm_judges.MAX_TOKENS = MAX_TOKENS
    llm_judges.LLM_THINKING_TIMEOUT_SECONDS = LLM_THINKING_TIMEOUT_SECONDS
    llm_judges.LLM_FALLBACK_TIMEOUT_SECONDS = LLM_FALLBACK_TIMEOUT_SECONDS
    llm_judges.JUDGE_TEMPERATURE = JUDGE_TEMPERATURE
    llm_judges.ENABLE_DESCRIPTION_COVERAGE_LOOP = ENABLE_DESCRIPTION_COVERAGE_LOOP
    llm_judges.DESCRIPTION_COVERAGE_ATTEMPTS = DESCRIPTION_COVERAGE_ATTEMPTS
    llm_judges.DESCRIPTION_COVERAGE_GOOD_ENOUGH_SCORE = (
        DESCRIPTION_COVERAGE_GOOD_ENOUGH_SCORE
    )
    llm_judges.INCLUDE_COVERAGE_JUDGE_NOTE = INCLUDE_COVERAGE_JUDGE_NOTE
    llm_judges.ENABLE_SHALLOW_RETRY = ENABLE_SHALLOW_RETRY
    llm_judges.ENABLE_MERMAID_DIAGRAMS = ENABLE_MERMAID_DIAGRAMS
    llm_judges.VALIDATE_MERMAID = VALIDATE_MERMAID
    llm_judges.MERMAID_REPAIR_ATTEMPTS = MERMAID_REPAIR_ATTEMPTS
    llm_judges.ENABLE_MERMAID_VISUAL_MATCH_LOOP = ENABLE_MERMAID_VISUAL_MATCH_LOOP
    llm_judges.MERMAID_VISUAL_MATCH_ATTEMPTS = MERMAID_VISUAL_MATCH_ATTEMPTS
    llm_judges.MERMAID_VISUAL_MATCH_GOOD_ENOUGH_SCORE = (
        MERMAID_VISUAL_MATCH_GOOD_ENOUGH_SCORE
    )
    llm_judges.INCLUDE_VISUAL_JUDGE_NOTE = INCLUDE_VISUAL_JUDGE_NOTE

    # mermaid_media.py
    mermaid_media.MERMAID_PUPPETEER_CONFIG_FILE = MERMAID_PUPPETEER_CONFIG_FILE
    mermaid_media.ENABLE_MERMAID_DIAGRAMS = ENABLE_MERMAID_DIAGRAMS
    mermaid_media.VALIDATE_MERMAID = VALIDATE_MERMAID
    mermaid_media.MERMAID_CLI_BIN = MERMAID_CLI_BIN
    mermaid_media.MERMAID_REPAIR_ATTEMPTS = MERMAID_REPAIR_ATTEMPTS
    mermaid_media.MERMAID_PARSE_TIMEOUT_SECONDS = MERMAID_PARSE_TIMEOUT_SECONDS
    mermaid_media.MERMAID_CLI_REQUIRED = MERMAID_CLI_REQUIRED
    mermaid_media.ENABLE_MERMAID_VISUAL_MATCH_LOOP = ENABLE_MERMAID_VISUAL_MATCH_LOOP
    mermaid_media.MERMAID_VISUAL_MATCH_ATTEMPTS = MERMAID_VISUAL_MATCH_ATTEMPTS
    mermaid_media.MERMAID_VISUAL_MATCH_GOOD_ENOUGH_SCORE = (
        MERMAID_VISUAL_MATCH_GOOD_ENOUGH_SCORE
    )
    mermaid_media.MERMAID_RENDER_TIMEOUT_SECONDS = MERMAID_RENDER_TIMEOUT_SECONDS
    mermaid_media.INCLUDE_VISUAL_JUDGE_NOTE = INCLUDE_VISUAL_JUDGE_NOTE

    # pipelines.py
    pipelines.MARKDOWN_FOLDER = MARKDOWN_FOLDER
    pipelines.FILE_CONCURRENCY = FILE_CONCURRENCY
    pipelines.OUTPUT_FILE = OUTPUT_FILE
    pipelines.CONCURRENCY = CONCURRENCY
    pipelines.OPENAI_MODEL = OPENAI_MODEL
    pipelines.TEMPERATURE = TEMPERATURE
    pipelines.LLM_THINKING_TIMEOUT_SECONDS = LLM_THINKING_TIMEOUT_SECONDS
    pipelines.LLM_FALLBACK_TIMEOUT_SECONDS = LLM_FALLBACK_TIMEOUT_SECONDS
    pipelines.ENABLE_SHALLOW_RETRY = ENABLE_SHALLOW_RETRY
    pipelines.ENABLE_DESCRIPTION_COVERAGE_LOOP = ENABLE_DESCRIPTION_COVERAGE_LOOP
    pipelines.DESCRIPTION_COVERAGE_ATTEMPTS = DESCRIPTION_COVERAGE_ATTEMPTS
    pipelines.DESCRIPTION_COVERAGE_GOOD_ENOUGH_SCORE = (
        DESCRIPTION_COVERAGE_GOOD_ENOUGH_SCORE
    )
    pipelines.INCLUDE_COVERAGE_JUDGE_NOTE = INCLUDE_COVERAGE_JUDGE_NOTE
    pipelines.MERMAID_PUPPETEER_CONFIG_FILE = MERMAID_PUPPETEER_CONFIG_FILE
    pipelines.ENABLE_MERMAID_DIAGRAMS = ENABLE_MERMAID_DIAGRAMS
    pipelines.VALIDATE_MERMAID = VALIDATE_MERMAID
    pipelines.MERMAID_CLI_BIN = MERMAID_CLI_BIN
    pipelines.MERMAID_REPAIR_ATTEMPTS = MERMAID_REPAIR_ATTEMPTS
    pipelines.MERMAID_CLI_REQUIRED = MERMAID_CLI_REQUIRED
    pipelines.ENABLE_MERMAID_VISUAL_MATCH_LOOP = ENABLE_MERMAID_VISUAL_MATCH_LOOP
    pipelines.MERMAID_VISUAL_MATCH_ATTEMPTS = MERMAID_VISUAL_MATCH_ATTEMPTS
    pipelines.MERMAID_VISUAL_MATCH_GOOD_ENOUGH_SCORE = (
        MERMAID_VISUAL_MATCH_GOOD_ENOUGH_SCORE
    )


async def process_markdown_folder():
    _sync_globals_to_modules()
    return await pipelines.process_markdown_folder()


async def process_sqlite_database(database_path: str, output_path: str | None = None):
    _sync_globals_to_modules()
    return await pipelines.process_sqlite_database(database_path, output_path)


def main():
    _sync_globals_to_modules()
    return pipelines.main()


if __name__ == "__main__":
    main()
