"""Entry point: uvicorn runner for the doc-parser server.

Bakes URL_PREFIX from .env into the frontend (frontend/src/url-prefix.js)
and rebuilds static/ before serving, so the SPA calls the prefixed API.
"""

import os
import subprocess
from pathlib import Path

import uvicorn
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent
FRONTEND = ROOT / "frontend"
PREFIX_JS = FRONTEND / "src" / "url-prefix.js"


def sync_frontend_prefix() -> None:
    # Keep explicit process/container environment variables authoritative.
    load_dotenv(ROOT / ".env", override=False)
    prefix = os.environ.get("URL_PREFIX", "").strip().rstrip("/")
    if prefix and not prefix.startswith("/"):
        prefix = f"/{prefix}"

    PREFIX_JS.write_text(
        "// Generated by main.py from URL_PREFIX in .env. Do not edit by hand.\n"
        f"export const URL_PREFIX = {prefix!r}\n"
    )
    print(f"[main] URL_PREFIX={prefix or '(none)'} -> {PREFIX_JS.relative_to(ROOT)}")

    # Rebuild static/ so the bundle picks up the new prefix.
    try:
        subprocess.run(["npm", "run", "build"], cwd=FRONTEND, check=True)
    except FileNotFoundError:
        print("[main] npm not found; serving the existing static/ build")


if __name__ == "__main__":
    sync_frontend_prefix()
    uvicorn.run("server:app", host="0.0.0.0", port=8080)
