import hashlib
import multiprocessing as mp
import os
import queue as queue_module
import shutil
import signal
import time
import traceback
import uuid
from contextlib import asynccontextmanager
from html import escape as html_escape
from pathlib import Path
from typing import Any, Optional

import image
import pdf
import requests
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel

CACHE_DIR = Path("./cache")
TEMP_DIR = Path("./temp")
CACHE_DIR.mkdir(exist_ok=True)
TEMP_DIR.mkdir(exist_ok=True)

MINERU_VENV_BIN = Path("/home/seigyo/llm-wiki/.venv/bin")

GPU_MEMORY_UTILIZATION = "0.05"
NVIDIA_INVOKE_URL = "http://10.160.144.101:51021/v1"
NVIDIA_API_KEY = (
    "<API_KEY>"
)
NVIDIA_MODEL = "openai/gpt-oss-120b"

IMAGE_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".webp",
    ".gif",
    ".bmp",
    ".tif",
    ".tiff",
}

MP_CONTEXT = mp.get_context("fork" if os.name == "posix" else "spawn")

tasks: dict[str, dict[str, Any]] = {}


class APIConfig(BaseModel):
    base_url: str = NVIDIA_INVOKE_URL
    api_key: str = NVIDIA_API_KEY
    model: str = NVIDIA_MODEL
    puppeteer_config_path: Optional[str] = (
        "/home/seigyo/llm-wiki-dist/puppeteer-config.json"
    )


def cleanup_stale_processing_dirs():
    for cache_path in CACHE_DIR.iterdir():
        if not cache_path.is_dir():
            continue

        marker = cache_path / ".processing"

        if marker.exists():
            print(f"[STARTUP] Removing stale processing cache: {cache_path}")
            shutil.rmtree(cache_path, ignore_errors=True)


def kill_process_forcefully(process: mp.Process, timeout: float = 5.0):
    if process.pid is None:
        return

    pid = process.pid

    if not process.is_alive():
        process.join(timeout=0.2)
        return

    print(f"[SHUTDOWN] Terminating process PID={pid}")

    try:
        if os.name == "posix":
            try:
                pgid = os.getpgid(pid)
                os.killpg(pgid, signal.SIGTERM)
            except ProcessLookupError:
                return
        else:
            process.terminate()
    except Exception as e:
        print(f"[WARN] SIGTERM failed for PID={pid}: {e}")

    start = time.time()

    while time.time() - start < timeout:
        if not process.is_alive():
            process.join(timeout=0.2)
            return
        time.sleep(0.1)

    if process.is_alive():
        print(f"[SHUTDOWN] Force killing process PID={pid}")

        try:
            if os.name == "posix":
                try:
                    pgid = os.getpgid(pid)
                    os.killpg(pgid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
            else:
                process.kill()
        except Exception as e:
            print(f"[WARN] SIGKILL failed for PID={pid}: {e}")

    process.join(timeout=1.0)


def shutdown_all_tasks():
    for task_id, meta in list(tasks.items()):
        process: mp.Process = meta["process"]
        cache_path = Path(meta["cache_path"])
        task_dir = Path(meta["task_dir"])

        if process.is_alive():
            kill_process_forcefully(process)

        print(f"[SHUTDOWN] Removing partial output for task {task_id}")
        shutil.rmtree(cache_path, ignore_errors=True)
        shutil.rmtree(task_dir, ignore_errors=True)


@asynccontextmanager
async def lifespan(app: FastAPI):
    cleanup_stale_processing_dirs()
    yield
    shutdown_all_tasks()


app = FastAPI(
    title="PDF to Markdown Processor",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def compute_pdf_hash(file_path: str) -> str:
    sha256 = hashlib.sha256()

    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)

    return sha256.hexdigest()


def find_single_markdown_file(mineru_dir: Path) -> Path:
    md_files = sorted(
        p for p in mineru_dir.rglob("*.md") if not p.name.endswith(".described.md")
    )

    if not md_files:
        raise RuntimeError("No Markdown file generated by PDF stage")

    return md_files[0]


def find_smallest_image(mineru_dir: Path) -> Optional[Path]:
    images = []

    for p in mineru_dir.rglob("*"):
        if not p.is_file():
            continue

        if p.suffix.lower() not in IMAGE_EXTENSIONS:
            continue

        try:
            if p.stat().st_size <= 0:
                continue
        except OSError:
            continue

        images.append(p)

    if not images:
        return None

    return min(images, key=lambda p: p.stat().st_size)


def vision_smoke_test(api_config: dict, image_path: Path) -> bool:
    try:
        data_url = image.image_file_to_data_url(str(image_path))
        response = requests.post(
            image.normalize_invoke_url(api_config["base_url"]),
            headers={
                "Authorization": f"Bearer {api_config['api_key']}",
                "Accept": "application/json",
                "Content-Type": "application/json",
            },
            json={
                "model": api_config["model"],
                "messages": [
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "text",
                                "text": "Reply OK.",
                            },
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": data_url,
                                },
                            },
                        ],
                    }
                ],
                "max_tokens": 8,
                "temperature": 0.0,
                "top_p": 0.95,
                "stream": False,
                "chat_template_kwargs": {"enable_thinking": True},
            },
            timeout=30.0,
        )
        response.raise_for_status()

        _ = image.get_response_text(response.json())
        return True

    except Exception as e:
        print(f"[WARN] Vision smoke test failed: {e}")
        return False


def build_empty_image_unit(data_url: str, alt: str) -> str:
    safe_src = html_escape(data_url, quote=True)
    safe_alt = html_escape(alt or "", quote=True)

    return (
        "\x3cimage-unit\x3e\n"
        "  \x3cimage-media\x3e\n"
        f'    \x3cimg src="{safe_src}" alt="{safe_alt}"\x3e\n'
        "  \x3c/image-media\x3e\n"
        "  \x3cimage-description\x3e\n"
        "  \x3c/image-description\x3e\n"
        "\x3c/image-unit\x3e"
    )


def fallback_embed_images(markdown_file: Path, final_md_path: Path):
    with open(markdown_file, "r", encoding="utf-8") as f:
        lines = f.readlines()

    image_line_indices = set(image.find_image_line_indices(lines))
    output_lines = []

    for i, line in enumerate(lines):
        if i not in image_line_indices:
            output_lines.append(line)
            continue

        has_newline = line.endswith("\n")
        line_body = line[:-1] if has_newline else line

        def replace_match(match):
            alt = match.group("alt")
            target = match.group("target")

            try:
                resolved = image.resolve_image_path(markdown_file, target)

                if image.is_remote_url(resolved):
                    return match.group(0)

                resolved_path = Path(resolved)

                if not resolved_path.exists() or not resolved_path.is_file():
                    return match.group(0)

                data_url = image.image_file_to_data_url(str(resolved_path))
                return build_empty_image_unit(data_url, alt)

            except Exception as e:
                print(f"[WARN] Failed to embed image {target}: {e}")
                return match.group(0)

        new_line = image.IMAGE_MARKDOWN_RE.sub(replace_match, line_body)

        if has_newline:
            new_line += "\n"

        output_lines.append(new_line)

    with open(final_md_path, "w", encoding="utf-8") as f:
        f.writelines(output_lines)


def worker_process(task_id: str, pdf_path: str, api_config: dict, cache_dir: str):
    import asyncio

    if os.name == "posix":
        os.setsid()

    if MINERU_VENV_BIN.exists():
        os.environ["PATH"] = (
            f"{MINERU_VENV_BIN}{os.pathsep}{os.environ.get('PATH', '')}"
        )
        os.environ["VIRTUAL_ENV"] = str(MINERU_VENV_BIN.parent)

    cache_path = Path(cache_dir)
    mineru_dir = cache_path / "mineru"
    mineru_dir.mkdir(parents=True, exist_ok=True)

    processing_marker = cache_path / ".processing"
    processing_marker.write_text("processing", encoding="utf-8")

    final_md_path = cache_path / "final.md"
    temp_pdf_dir = Path(pdf_path).parent

    try:
        pdf.PDF_DIR = temp_pdf_dir
        pdf.OUTPUT_DIR = mineru_dir
        pdf.GPU_MEMORY_UTILIZATION = GPU_MEMORY_UTILIZATION

        expected_output_folder = mineru_dir / Path(pdf_path).stem

        if not expected_output_folder.exists():
            try:
                pdf.main()
            except SystemExit as e:
                if e.code != 0:
                    raise RuntimeError(f"pdf.main() exited with code {e.code}")

        markdown_file = find_single_markdown_file(mineru_dir)
        smallest_image = find_smallest_image(mineru_dir)

        if smallest_image is None:
            print(f"[INFO] Task {task_id}: no images found")
            shutil.copyfile(markdown_file, final_md_path)
            processing_marker.unlink(missing_ok=True)
            return str(final_md_path)

        print(
            f"[INFO] Task {task_id}: smallest image is {smallest_image} "
            f"({smallest_image.stat().st_size} bytes)"
        )

        vision_ok = vision_smoke_test(api_config, smallest_image)

        if vision_ok:
            try:
                image.MARKDOWN_FOLDER = str(mineru_dir)
                image.OPENAI_BASE_URL = api_config["base_url"]
                image.OPENAI_API_KEY = api_config["api_key"]
                image.OPENAI_MODEL = api_config["model"]
                image.MERMAID_PUPPETEER_CONFIG_FILE = api_config.get(
                    "puppeteer_config_path",
                    "/home/seigyo/llm-wiki/puppeteer-config.json",
                )

                image.CONCURRENCY = 2
                image.FILE_CONCURRENCY = 1

                asyncio.run(image.process_markdown_folder())

                described_md = markdown_file.with_name(
                    f"{markdown_file.stem}.described.md"
                )

                if not described_md.exists():
                    raise RuntimeError(
                        f"image.py completed but described file was not found: {described_md}"
                    )

                shutil.copyfile(described_md, final_md_path)
                processing_marker.unlink(missing_ok=True)
                return str(final_md_path)

            except Exception as e:
                print(f"[WARN] image.py failed, fallback enabled: {e}")

        fallback_embed_images(markdown_file, final_md_path)
        processing_marker.unlink(missing_ok=True)
        return str(final_md_path)

    finally:
        shutil.rmtree(temp_pdf_dir, ignore_errors=True)


def worker_entry(
    task_id: str,
    pdf_path: str,
    api_config: dict,
    cache_dir: str,
    result_queue,
):
    try:
        result_path = worker_process(task_id, pdf_path, api_config, cache_dir)

        result_queue.put(
            {
                "ok": True,
                "result_path": result_path,
            }
        )

    except BaseException as e:
        cache_path = Path(cache_dir)

        print(f"[ERROR] Task {task_id} failed: {e}")
        print(traceback.format_exc())

        shutil.rmtree(cache_path, ignore_errors=True)

        result_queue.put(
            {
                "ok": False,
                "error": str(e),
                "traceback": traceback.format_exc(),
            }
        )


def refresh_task_status(task_id: str):
    if task_id not in tasks:
        return None

    meta = tasks[task_id]
    process: mp.Process = meta["process"]
    result_queue = meta["queue"]
    final_md_path = Path(meta["cache_path"]) / "final.md"

    while True:
        try:
            msg = result_queue.get_nowait()
        except queue_module.Empty:
            break

        meta["last_message"] = msg

        if msg.get("ok"):
            meta["status"] = "completed"
        else:
            meta["status"] = "failed"
            meta["error"] = msg.get("error", "Unknown error")

    if final_md_path.exists():
        meta["status"] = "completed"
        return meta

    if process.is_alive():
        meta["status"] = "processing"
        return meta

    if process.exitcode is not None:
        if meta.get("status") not in {"completed", "failed"}:
            meta["status"] = "failed"
            meta["error"] = f"Worker exited with code {process.exitcode}"

    return meta


@app.post("/upload")
async def upload_pdf(
    file: UploadFile = File(...),
    base_url: str = Form(NVIDIA_INVOKE_URL),
    api_key: str = Form(NVIDIA_API_KEY),
    model: str = Form(NVIDIA_MODEL),
    puppeteer_config_path: Optional[str] = Form(
        "/home/seigyo/llm-wiki/puppeteer-config.json"
    ),
):
    if not file.filename or not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported")

    pending_dir = TEMP_DIR / "pending"
    pending_dir.mkdir(parents=True, exist_ok=True)

    safe_filename = Path(file.filename).name
    pending_pdf_path = pending_dir / f"{uuid.uuid4().hex}_{safe_filename}"

    sha256 = hashlib.sha256()

    with open(pending_pdf_path, "wb") as f:
        while chunk := await file.read(8192):
            f.write(chunk)
            sha256.update(chunk)

    pdf_hash = sha256.hexdigest()

    cache_path = CACHE_DIR / pdf_hash
    final_md_path = cache_path / "final.md"

    if final_md_path.exists():
        pending_pdf_path.unlink(missing_ok=True)

        return {
            "task_id": pdf_hash,
            "status": "completed",
            "message": "Returned from cache",
            "result_url": f"/result/{pdf_hash}",
        }

    if pdf_hash in tasks:
        meta = refresh_task_status(pdf_hash)

        if meta and meta.get("status") in {"queued", "processing"}:
            pending_pdf_path.unlink(missing_ok=True)

            return {
                "task_id": pdf_hash,
                "status": meta["status"],
                "message": "Task already running",
            }

    task_dir = TEMP_DIR / pdf_hash
    task_dir.mkdir(parents=True, exist_ok=True)

    final_temp_pdf = task_dir / safe_filename
    shutil.move(str(pending_pdf_path), str(final_temp_pdf))

    cache_path.mkdir(parents=True, exist_ok=True)

    api_config = {
        "base_url": base_url,
        "api_key": api_key,
        "model": model,
        "puppeteer_config_path": puppeteer_config_path,
    }

    result_queue = MP_CONTEXT.Queue()

    process = MP_CONTEXT.Process(
        target=worker_entry,
        args=(
            pdf_hash,
            str(final_temp_pdf),
            api_config,
            str(cache_path),
            result_queue,
        ),
        daemon=False,
    )

    tasks[pdf_hash] = {
        "process": process,
        "queue": result_queue,
        "status": "queued",
        "cache_path": str(cache_path),
        "task_dir": str(task_dir),
        "error": None,
    }

    process.start()

    return {
        "task_id": pdf_hash,
        "status": "queued",
        "message": "Task submitted",
    }


@app.get("/status/{task_id}")
async def get_status(task_id: str):
    final_md_path = CACHE_DIR / task_id / "final.md"

    if task_id not in tasks:
        if final_md_path.exists():
            return {
                "task_id": task_id,
                "status": "completed",
                "message": "Available in cache",
            }

        raise HTTPException(status_code=404, detail="Task not found")

    meta = refresh_task_status(task_id)

    response = {
        "task_id": task_id,
        "status": meta["status"],
    }

    if meta.get("error"):
        response["error"] = meta["error"]

    if meta["status"] == "completed":
        response["result_url"] = f"/result/{task_id}"

    return response


@app.get("/result/{task_id}")
async def get_result(task_id: str):
    final_md_path = CACHE_DIR / task_id / "final.md"

    if not final_md_path.exists():
        if task_id in tasks:
            meta = refresh_task_status(task_id)

            if meta.get("status") == "failed":
                raise HTTPException(
                    status_code=500,
                    detail=meta.get("error", "Task failed"),
                )

        raise HTTPException(status_code=404, detail="Result not ready or not found")

    return FileResponse(
        final_md_path,
        media_type="text/markdown",
        filename=f"{task_id}.md",
    )
