export const STR = {
  ja: {
    unsafeImg: '安全でない画像ソースをブロックしました。',
    imgFailed:
      '画像の読み込みまたはデコードに失敗しました。base64 データが不完全、または破損している可能性があります。',
    editingStatus: 'Markdown を直接編集しています。画像ブロックは専用エディタで編集できます。',
    unsavedAnswer: '未保存の回答。編集して wiki に追加してください。',
    draftStatus: '下書き。編集してグラフに追加してください。',
    dirtyStatus: '未保存の変更。保存してグラフのこのノードを更新します。',
    editButtonOnly: '編集するには編集ボタンを押してください。',
    editing: '編集中',
    answerDraft: '回答の下書き',
    draft: '下書き',
    agentNote: 'エージェントノート',
    sourceNote: 'ソースノート',
    edit: '編集',
    cancel: 'キャンセル',
    adding: '追加中...',
    addToWiki: 'wiki に追加',
    addToGraph: 'グラフに追加',
    saving: '保存中...',
    save: '保存',
    export: 'ダウンロード',
    exportTitle: 'Markdown をダウンロード',
    prevChunk: '前へ',
    nextChunk: '次へ',
    untitled: '無題',
    del: '削除',
    pagesChain: 'ページ、チェーン順に追加:',
    references: '参照',
    referenceLabel: '参照',
    imageBlock: '画像',
    uploadReplaceImage: '画像をアップロード / 置換',
    removeImageData: '画像データを削除',
    imageDescription: '画像説明',
    imageDescriptionRequired: '画像がある場合、説明は必須です。',
    noImageData: '画像データはありません。',
    invalidImages: '説明がない画像があります。',
  },
  en: {
    unsafeImg: 'Blocked an unsafe image source.',
    imgFailed:
      'The image failed to load or decode. The base64 data may be incomplete or corrupted.',
    editingStatus:
      'Editing Markdown directly. Image blocks can be edited with the dedicated image editor.',
    unsavedAnswer: 'Unsaved answer. Edit it, then add it to the wiki.',
    draftStatus: 'Draft. Edit it, then add it to the graph.',
    dirtyStatus: 'Unsaved changes. Save to update this node in the graph.',
    editButtonOnly: 'Use the Edit button to edit this document.',
    editing: 'Editing',
    answerDraft: 'Answer draft',
    draft: 'Draft',
    agentNote: 'Agent note',
    sourceNote: 'Source note',
    edit: 'Edit',
    cancel: 'Cancel',
    adding: 'Adding...',
    addToWiki: 'Add to wiki',
    addToGraph: 'Add to graph',
    saving: 'Saving...',
    save: 'Save',
    export: 'Download',
    exportTitle: 'Download Markdown',
    prevChunk: 'Previous',
    nextChunk: 'Next',
    untitled: 'untitled',
    del: 'Delete',
    pagesChain: 'pages, appended in chain order:',
    references: 'References',
    referenceLabel: 'Reference',
    imageBlock: 'Image',
    uploadReplaceImage: 'Upload / replace image',
    removeImageData: 'Remove image data',
    imageDescription: 'Image description',
    imageDescriptionRequired: 'Description is required when an image exists.',
    noImageData: 'No image data.',
    invalidImages: 'Some images are missing descriptions.',
  },
}
